     /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package complexadministration;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.Date;
import javax.swing.table.DefaultTableModel;




/**
 *
 * @author AK
 */
public class officerooms extends javax.swing.JFrame {
     java.util.Date dob;
      java.sql.Date sqldate;
      java.util.Date joineddate;
     java.sql.Date sqldate1;
     java.util.Date month;
     java.sql.Date sqldate2;
     
     
     
     
    

    /**
     * Creates new form officerooms
     */
    public officerooms() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        combogn = new javax.swing.JComboBox<>();
        txtcn = new javax.swing.JTextField();
        txtadd = new javax.swing.JTextField();
        txtan = new javax.swing.JTextField();
        txtpn = new javax.swing.JTextField();
        txten = new javax.swing.JTextField();
        txtadvance = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        txtdob = new com.toedter.calendar.JDateChooser();
        txtjd = new com.toedter.calendar.JDateChooser();
        comborn = new javax.swing.JComboBox<>();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tendet = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        btntendet = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtrnt = new javax.swing.JTextField();
        txtn = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btnsavepay = new javax.swing.JButton();
        btnbackpay = new javax.swing.JButton();
        comboroom = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtmonth = new com.toedter.calendar.JDateChooser();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtpd = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        txtcno = new javax.swing.JTextField();
        checkpaid = new javax.swing.JCheckBox();
        btnuppay = new javax.swing.JButton();
        paytab = new javax.swing.JButton();
        btndelpay = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtadh = new javax.swing.JTextField();
        btnclearpay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel26.setText("ROOM NUMBER");

        jLabel27.setText("NAME");

        jLabel28.setText("DATE OF BIRTH");

        jLabel29.setText("GENDER");

        jLabel30.setText("CONTACT NUMBER");

        jLabel31.setText("ADDRESS");

        jLabel32.setText("ADHAR NUMBER");

        jLabel33.setText("PAN NUMBER");

        jLabel34.setText("JOINED DATE");

        jLabel36.setText("ELECTRICITY NUMBER");

        jLabel37.setText("ADVANCE");

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel38.setText("ADD TENANT DETAILS");

        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnameKeyReleased(evt);
            }
        });

        combogn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "male", "female" }));

        txtcn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcnKeyTyped(evt);
            }
        });

        txtan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtanKeyTyped(evt);
            }
        });

        txtadvance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtadvanceKeyTyped(evt);
            }
        });

        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        comborn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setText("DELETE");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnsearch.setText("SEARCH");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Only alphabets are acceptable");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(300, 300, 300)
                                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtjd, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtpn, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                        .addComponent(txtadd, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                        .addComponent(txten, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                        .addComponent(txtadvance)))))
                        .addContainerGap(423, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(comborn, 0, 242, Short.MAX_VALUE)
                                        .addComponent(txtname, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
                                    .addComponent(txtan, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcn, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combogn, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnupdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnsave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btndelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnclear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(140, 140, 140))
                            .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comborn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(combogn, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtcn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtadd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtdob, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(txtjd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txten, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtadvance, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(121, 121, 121))
        );

        jTabbedPane1.addTab("ADD TENANT DETAILS", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        tendet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ROOMNUM", "NAME", "DOB", "GENDER", "CONTACTNUM", "ADDRESS", "ADHARNUM", "PANNUM", "JOINEDDATE", "ADVANCE"
            }
        ));
        jScrollPane1.setViewportView(tendet);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setText("TENANT DETAILS");

        btntendet.setText("VIEW");
        btntendet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntendetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(345, 345, 345)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(361, 361, 361)
                                .addComponent(btntendet)))
                        .addGap(0, 385, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btntendet)
                .addContainerGap(240, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("TEANANT DETAILS", jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));

        jLabel14.setText("ROOM NUMBER");

        jLabel15.setText("NAME");

        jLabel18.setText("RENT");

        txtrnt.setText(" ");

        txtn.setText(" ");
        txtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnKeyPressed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setText("PAYMENT INFORMATION OF TENANTS");

        btnsavepay.setText("SAVE");
        btnsavepay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsavepayActionPerformed(evt);
            }
        });

        btnbackpay.setText("BACK");
        btnbackpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackpayActionPerformed(evt);
            }
        });

        comboroom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));

        jLabel12.setText("MONTH");

        txtpd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ADHARNUM", "NAME", "ROOMNUM", "CONTACTNUM", "RENT", "MONTH", "PAID"
            }
        ));
        jScrollPane4.setViewportView(txtpd);

        jLabel13.setText("CONTACT NUMBER");

        txtcno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcnoActionPerformed(evt);
            }
        });
        txtcno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcnoKeyTyped(evt);
            }
        });

        checkpaid.setText("paid");

        btnuppay.setText("UPDATE");
        btnuppay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuppayActionPerformed(evt);
            }
        });

        paytab.setText("VIEW");
        paytab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paytabActionPerformed(evt);
            }
        });

        btndelpay.setText("DELETE");
        btndelpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelpayActionPerformed(evt);
            }
        });

        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("ADHARNUM");

        txtadh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtadhKeyTyped(evt);
            }
        });

        btnclearpay.setText("CLEAR");
        btnclearpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearpayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnsavepay)
                        .addGap(18, 18, 18)
                        .addComponent(btnuppay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndelpay)
                        .addGap(18, 18, 18)
                        .addComponent(btnclearpay, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnbackpay))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtn)
                                            .addComponent(txtadh)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(comboroom, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtcno, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(checkpaid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtrnt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(8, 8, 8)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(paytab)
                .addGap(278, 278, 278))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtadh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboroom, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcno, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtrnt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(checkpaid)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsavepay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnuppay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btndelpay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnclearpay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(201, 201, 201))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(paytab)
                        .addGap(27, 27, 27)
                        .addComponent(btnbackpay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("PAYMENT INFORMATION", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        //TODO add your handling code here:
        int roomnum=Integer.parseInt((String) comborn.getSelectedItem());
        String name=txtname.getText();
        dob=txtdob.getDate();
        sqldate=new java.sql.Date(dob.getTime());
        String gender =(String) combogn.getSelectedItem();
        String contactnum=txtcn.getText();
        String address=txtadd.getText();
        String adharnum=txtan.getText();
        String pannum=txtpn.getText();
        joineddate=txtjd.getDate();
        sqldate1=new java.sql.Date(joineddate.getTime());   
        String electricitynum=txten.getText();
        Double advance=Double.parseDouble(txtadvance.getText());
        
        
        
        
        try
        {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/rachana","app","APP");
            String query="Insert into offaddnewten(ROOMNUM,NAME,DOB,GENDER,CONTACTNUM,ADDRESS,ADHARNUM,PANNUM,JOINEDDATE,ELECTRICITYNUM,ADVANCE)values(?,?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement p;
            p=con.prepareStatement(query);
            java.util.Date d=new java .util.Date();
            SimpleDateFormat df=new SimpleDateFormat("dd-MM-YYYY");
            
            if(comborn.getSelectedItem().equals("")||txtname.getText().equals("")||txtdob.getDate().equals("")||txtcn.getText().equals("")||txtadd.getText().equals("")||txtan.getText().equals("")||txtpn.getText().equals("")||txtjd.getDate().equals("")||txtadvance.getText().equals(""))
            {
                 JOptionPane.showMessageDialog(null,"Fill all the details");
            }
            
                        
            p.setInt(1,roomnum );//1
            p.setString(2,name );//2
            p.setDate(3,sqldate);//3
            p.setString(4,gender);//4
            p.setString(5,contactnum);//5
            p.setString(6,address );//6
            p.setString(7,adharnum );//7
            p.setString(8,pannum );//8
            p.setDate(9,sqldate1);//9
            p.setString(10,electricitynum);//10
            p.setDouble(11,advance );//11
            p.executeUpdate();
            JOptionPane.showMessageDialog(null," Data inserted sucessfully");
            
            
                       
        }
        
        catch(HeadlessException | SQLException ex)
                {
                    Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, ex);
                }
                

        
        
        
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
          homepage h =new homepage();
          h.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnsavepayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsavepayActionPerformed
        // TODO add your handling code here:
        String adharnum=txtadh.getText();
        String name=txtn.getText();
        String roomnum=(String) comboroom.getSelectedItem();
        String contactnum=txtcno.getText();
        String rent=txtrnt.getText();
        month=txtmonth.getDate();
        sqldate2=new java.sql.Date(month.getTime());
        String paid;
        if(checkpaid.isSelected())
        {
            paid="yes";
        }
        else
        {
            paid="no";
        }
        java.util.Date d=new java .util.Date();
        SimpleDateFormat df=new SimpleDateFormat("dd-MM-YYYY");
        
       
        try
        {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/rachana","app","APP");
            String query="insert into offpay(NAME,ROOMNUM,CONTACTNUM,RENT,MONTH,PAID,ADHARNUM)values(?,?,?,?,?,?,?)";
            PreparedStatement p;
            p=con.prepareStatement(query);
           
            
            p.setString(1,name);
            p.setString(2,roomnum);
            p.setString(3,contactnum);
            p.setString(4,rent);
            p.setDate(5,sqldate2);
            p.setString(6,paid);
            p.setString(7, adharnum);
            p.executeUpdate();
            JOptionPane.showMessageDialog(null," Data inserted sucessfully");
            
            
            
        }
        catch(Exception ex)
                {
                    Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
                }
        
                
        
    }//GEN-LAST:event_btnsavepayActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        int roomnum=Integer.parseInt((String) comborn.getSelectedItem());
        String name=txtname.getText();
        dob=txtdob.getDate();
        sqldate=new java.sql.Date(dob.getTime());
        String gender =(String) combogn.getSelectedItem();
        String contactnum=txtcn.getText();
        String address=txtadd.getText();
        String adharnum=txtan.getText();
        String pannum=txtpn.getText();
        joineddate=txtjd.getDate();
        sqldate1=new java.sql.Date(joineddate.getTime());   
        String electricitynum=txten.getText();
        Double advance=Double.parseDouble(txtadvance.getText());
        
         try
        {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/rachana","app","APP");
            Statement st=con.createStatement();
            PreparedStatement p = con.prepareStatement("update offaddnewten set roomnum=?,name=?,dob=?,gender=?,contactnum=?,"
                    + "address=?,pannum=?,joineddate=?,electricitynum=?,advance=? where adharnum=?");
            
            java.util.Date d=new java .util.Date();
            SimpleDateFormat df=new SimpleDateFormat("dd-MM-YYYY");
                        
            p.setInt(1, roomnum);//1
            p.setString(2,name );//2
            p.setDate(3,sqldate);//3
            p.setString(4,gender);//4
            p.setString(5,contactnum);//5
            p.setString(6,address );//6
            p.setString(11,adharnum );//7
            p.setString(7,pannum );//8
            p.setDate(8,sqldate1 );//9
            p.setString(9,electricitynum);//10
            p.setDouble(10,advance );//11
            p.executeUpdate();
            JOptionPane.showMessageDialog(null,"sucessfully Updated");
            
            
                       
        }
        catch(SQLException ex)
                {
                    Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
                }
        
        
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        String adharnum=txtan.getText();
        try
        {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/rachana","app","APP");
            PreparedStatement p = con.prepareStatement("delete from offaddnewten where adharnum='"+adharnum+"'");
            p.executeUpdate();
            JOptionPane.showMessageDialog(null,"sucessfuly deleted");
        }
        catch(SQLException ex)
        {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        
        try
        {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/rachana","app","APP");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from offaddnewten WHERE adharnum='"+txtan.getText()+"'");
            if(txtan.getText().equals(""))
            {
                JOptionPane.showMessageDialog(null,"ENTER ADHARNUMBER");
            }
            else
            {
                if(rs.next())
                {
                    comborn.setSelectedItem(rs.getString(1));
                    txtname.setText(rs.getString(2));
                    txtdob.setDate(rs.getDate(3));
                    combogn.setSelectedItem(rs.getString(4));
                    txtcn.setText(rs.getString(5));
                    txtadd.setText(rs.getString(6));
                    //txtan.setText(rs.getString(7));
                    txtpn.setText(rs.getString(8));
                    txtjd.setDate(rs.getDate(9));
                    txten.setText(rs.getString(10));
                    txtadvance.setText(rs.getString(11));
                }
                else{
                   JOptionPane.showMessageDialog(null,"Does not exist");
                }
            }
        }
        catch(Exception ex)
        {
             Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
        
       
            
        
        
    }//GEN-LAST:event_btnsearchActionPerformed

    private void txtcnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcnoActionPerformed

    private void btnbackpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackpayActionPerformed
        // TODO add your handling code here:
         homepage h =new homepage();
          h.setVisible(true);
          this.dispose();
        
    }//GEN-LAST:event_btnbackpayActionPerformed

    private void btntendetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntendetActionPerformed
        // TODO add your handling code here:
        
        try
        {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/rachana","app","APP");
            DefaultTableModel model =new DefaultTableModel(new String[]{"roomnum","name","dob","gender","contactnum","address","adharnum","pannum","joineddate","electricitynum","advance"},0);
            String sql="select * from offaddnewten";
            Statement st= con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while (rs.next())
            {
                String r =rs.getString("roomnum");
                String n =rs.getString("name");
                String d =rs.getString("dob");
                String g=rs.getString("gender");
                String c =rs.getString("contactnum");
                String add =rs.getString("address");
                String adh =rs.getString("adharnum");
                String pan =rs.getString("pannum");
                String jd =rs.getString("joineddate");
                String en=rs.getString("electricitynum");
                String a =rs.getString("advance");
                model.addRow(new Object[]{r,n,d,g,c,add,adh,pan,jd,en,a});
            }
            tendet.setModel(model);
            
        }
        catch(Exception ex)
        {
            ex.printStackTrace(); 
            System.out.println(ex); 
            System.out.println("complexadminstration.BtnInsertActionPerformed()"); 

        }
    }//GEN-LAST:event_btntendetActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
        Date date=null;
        comborn.setSelectedItem("1");
        txtname.setText("");
        txtdob.setDate(date);
        combogn.setSelectedItem("male");
        txtcn.setText("");
        txtadd.setText("");
        txtan.setText("");
        txtpn.setText("");
        txtjd.setDate(date);
        txten.setText("");
        txtadvance.setText("");
        
    }//GEN-LAST:event_btnclearActionPerformed

    private void paytabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paytabActionPerformed
        // TODO add your handling code here:
        try
        {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/rachana","app","APP");
            DefaultTableModel m =new DefaultTableModel(new String[]{"name","roomnum","contactnum","rent","month","paid","adharnum"},0);
            String sql ="select * from offpay";
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next())
            {
                
                String n =rs.getString("name");
                String r =rs.getString("roomnum");
                String rnt =rs.getString("contactnum");
                String cn=rs.getString("rent");
                String mn =rs.getString("month");
                String p =rs.getString("paid");
                String a=rs.getString("adharnum");
                
                m.addRow(new Object[]{n,r,rnt,cn,mn,p,a});
                
                
            }
            txtpd.setModel(m);
                 
        }
        catch(Exception ex)
        {
            ex.printStackTrace(); 
            System.out.println(ex); 
            System.out.println("StudentRegistration.BtnInsertActionPerformed()"); 
        }
    }//GEN-LAST:event_paytabActionPerformed

    private void btnuppayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuppayActionPerformed
        // TODO add your handling code here:
        String adharnum=txtadh.getText();
        String name=txtn.getText();
        String roomnum =(String) comboroom.getSelectedItem();
        String contactnum=txtcno.getText();
        String rent=txtrnt.getText();
        month=txtmonth.getDate();
        sqldate2=new java.sql.Date(month.getTime());
        String paid=checkpaid.getText();
        
         
         try
         {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/rachana","app","APP");
            Statement st=con.createStatement();
            PreparedStatement p = con.prepareStatement("update offpay set name=?,roomnum=?,contactnum=?,rent=?,month=?,paid=?WHERE adharnum=?");
            
            java.util.Date d=new java .util.Date();
            SimpleDateFormat df=new SimpleDateFormat("dd-MM-YYYY");
            
            p.setString(7,adharnum);
            p.setString(1,name);
            p.setString(2,roomnum);
            p.setString(3,contactnum);
            p.setString(4,rent);
            p.setDate(5,sqldate2);
            p.setString(6,paid);
           
           
           
           
                   
            p.executeUpdate();
            JOptionPane.showMessageDialog(null,"sucessfully Updated");
            
            
                       
        }
        catch(SQLException ex)
                {
                    Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
                }
        
        
    }//GEN-LAST:event_btnuppayActionPerformed

    private void btndelpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelpayActionPerformed
        // TODO add your handling code here:
        
        try
        {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/rachana","app","APP");
            PreparedStatement p = con.prepareStatement("delete from offpay where adharnum='"+txtadh.getText()+"'");
            p.executeUpdate();
            JOptionPane.showMessageDialog(null,"sucessfuly deleted");
        }
        catch(SQLException ex)
        {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        }
          
    }//GEN-LAST:event_btndelpayActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try
        {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/rachana","app","APP");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from offpay WHERE adharnum='"+txtadh.getText()+"'");
            if(rs.next())
            {
                comboroom.setSelectedItem(rs.getString(2));
                txtn.setText(rs.getString(1));
                txtcno.setText(rs.getString(3));
                txtrnt.setText(rs.getString(4));
                txtmonth.setDate(rs.getDate(5));
                if (rs.getString(6).equals("yes"))
                {
                    checkpaid.setSelected(true);
                }
                txtadh.setText(rs.getString(7));
                //checkpaid.setText(rs.getString(6));
                
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Does not exist");
            }
        }
        catch(Exception ex)
        {
             Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnclearpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearpayActionPerformed
        // TODO add your handling code here:
        Date date=null;
        comboroom.setSelectedItem("1");
        txtcno.setText("");
        txtadh.setText("");
        txtn.setText("");
        txtrnt.setText("");
        txtadh.setText("");
        txtmonth.setDate(date);
        checkpaid.setSelected(false);
        
    }//GEN-LAST:event_btnclearpayActionPerformed

    private void txtnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyReleased
        
    }//GEN-LAST:event_txtnameKeyReleased

    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if (Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
            txtname.setEditable(true);
        }
        else
        {
            txtname.setEditable(false);
        }
               
    }//GEN-LAST:event_txtnameKeyPressed

    private void txtcnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcnKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
                
    }//GEN-LAST:event_txtcnKeyTyped

    private void txtanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtanKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(!Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
            
    }//GEN-LAST:event_txtanKeyTyped

    private void txtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnKeyPressed
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if (Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c))
        {
            txtname.setEditable(true);
        }
        else
        {
            txtname.setEditable(false);
            JOptionPane.showMessageDialog(null,"only letters are acceptable");
        }
    }//GEN-LAST:event_txtnKeyPressed

    private void txtadhKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtadhKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
          
    }//GEN-LAST:event_txtadhKeyTyped

    private void txtcnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcnoKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
          
    }//GEN-LAST:event_txtcnoKeyTyped

    private void txtadvanceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtadvanceKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar();
        if(!Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_txtadvanceKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(officerooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(officerooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(officerooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(officerooms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new officerooms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnbackpay;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnclearpay;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btndelpay;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsavepay;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btntendet;
    private javax.swing.JButton btnupdate;
    private javax.swing.JButton btnuppay;
    private javax.swing.JCheckBox checkpaid;
    private javax.swing.JComboBox<String> combogn;
    private javax.swing.JComboBox<String> comborn;
    private javax.swing.JComboBox<String> comboroom;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton paytab;
    private javax.swing.JTable tendet;
    private javax.swing.JTextField txtadd;
    private javax.swing.JTextField txtadh;
    private javax.swing.JTextField txtadvance;
    private javax.swing.JTextField txtan;
    private javax.swing.JTextField txtcn;
    private javax.swing.JTextField txtcno;
    private com.toedter.calendar.JDateChooser txtdob;
    private javax.swing.JTextField txten;
    private com.toedter.calendar.JDateChooser txtjd;
    private com.toedter.calendar.JDateChooser txtmonth;
    private javax.swing.JTextField txtn;
    private javax.swing.JTextField txtname;
    private javax.swing.JTable txtpd;
    private javax.swing.JTextField txtpn;
    private javax.swing.JTextField txtrnt;
    // End of variables declaration//GEN-END:variables
}
